web-project/BASDAT_TK3_F04/urls.py
from django.contrib import admin
from django.urls import include, path
from django import urls
from cr_histori_hewan.views import list_histori_hewan, produksi_hewan

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('crud-produk/', include('crud_produk.urls')),
    path('crud-paket-koin/', include('crud_paket_koin.urls')),
    path('cr-transaksi-pembelian-koin/', include('cr_transaksi_pembelian_koin.urls')),
    path('cr-transaksi-upgrade-lumbung/', include('cr_transaksi_update_lumbung.urls')),
    path('cr-histori-tanaman/', include('cr_histori_tanaman.urls')),
    path('crud-pesanan/', include('crud_pesanan.urls')),
    path('cr-histori-hewan/', include('cr_histori_hewan.urls')),
    path('cr-histori-penjualan/', include('cr_histori_penjualan.urls')),
    path('crud-produksi/', include('crud_produksi.urls')),
    path('cr-histori-pmakanan/', include('cr_histori_pmakanan.urls')),
    path('crud-aset/', include('crud_aset.urls')),
    path('r-koleksi-aset/', include('r_koleksi_aset.urls')),
    path('cr-transaksi-pembelian-aset/', include('cr_transaksi_pembelian_aset.urls')),
]

web-project/crud_paket_koin/urls.py
from django.urls import path

from . import views

app_name = 'crud_paket_koin'

urlpatterns = [
    path('list-paket-koin', views.listPaketKoin, name='list-paket-koin'),
    path('create-paket-koin', views.buatPaketKoin, name='create-paket-koin'),
    path('update-paket-koin/<slug:slug>', views.updatePaketKoin, name='update-paket-koin'),
    path('delete-paket-koin/<slug:slug>', views.deletePaketKoin, name='delete-paket-koin'),
]

web-project/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='landing'),
    path('registrasi', views.registrasi, name='registrasi'),
    path('registrasi-pengguna', views.registrasiPengguna, name='registrasi-pengguna'),
    path('registrasi-admin', views.registrasiAdmin, name='registrasi-admin'),
    path('login', views.login, name='login'),
    path('profile', views.loggedInView, name='view'),
    path('logout', views.logout, name='logout'),
    path('index', views.login, name='home'),
    path('isi-lumbung', views.isiLumbung, name='isi-lumbung'),
]

web-project/crud_paket_koin/models.py
from django.db import models

# Create your models here.

web-project/crud_paket_koin/forms.py
from django import forms

class BuatPaketKoin(forms.Form):
    JumlahKoin = forms.IntegerField(label='Jumlah')
    Harga = forms.IntegerField(label='Harga')

class UpdatePaketKoin(forms.Form):
    # JumlahKoin = forms.IntegerField(label='Jumlah')
    Harga = forms.IntegerField(label='Harga')

class DeletePaketKoin(forms.Form):
    JumlahKoin = forms.IntegerField(label='Jumlah')

web-project/crud_paket_koin/views.py
from ntpath import join
import re
from unittest import result
from django.shortcuts import render
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.db import connection
from collections import namedtuple
from .forms import *

# Create your views here.

def tupleFetch(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def listPaketKoin(request):
   if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        bisaDelete = []
        coba = []

        try:
            if (request.session['role'] == ['admin']):
                cursor.execute("SELECT * FROM hiday.PAKET_KOIN")
                result = tupleFetch(cursor)
                role = "admin"
                cursor.execute("SELECT jumlah_koin FROM hiday.PAKET_KOIN WHERE jumlah_koin NOT IN (SELECT paket_koin FROM hiday.TRANSAKSI_PEMBELIAN_KOIN);")
                bisaDelete = tupleFetch(cursor)

                coba = []

                if (len(bisaDelete)>0):
                    for i in (bisaDelete):
                        for j in (result):
                            if(j.jumlah_koin == i.jumlah_koin):
                                coba.append(j.jumlah_koin)
            
            
            else:
                cursor.execute("SELECT * FROM hiday.PAKET_KOIN")
                result = tupleFetch(cursor)
                role = "pengguna"

        except Exception as e:
            print(e)
        
        finally:
            cursor.close()
            temp = {}
            for i in range(len(result)):
                temp[i+1] = result[i]
                
            resultNum = list(temp.items())
            # print(resultNum)

        return render(request, 'list_paket_koin.html', {"result" : resultNum, "role" : role, "coba":coba})

   else:
        return HttpResponseRedirect('/login')

def buatPaketKoin(request):
    role = ''
    formBuatPaket = BuatPaketKoin(request.POST)
  
    if (request.session['role'] == ['admin']):
        role = "admin"

    else:
        role = "pengguna"

    if (formBuatPaket.is_valid() and request.method == 'POST'):
        jumlahKoin = formBuatPaket.cleaned_data['JumlahKoin']
        harga = formBuatPaket.cleaned_data['Harga']

        try:
            cursor = connection.cursor()
            cursor.execute("INSERT INTO hiday.PAKET_KOIN VALUES("+ str(jumlahKoin) +"," + str(harga)+ ");")
            
        except Exception as e:
            print(e)
            cursor.close()

        finally:
            cursor.close()

        return HttpResponseRedirect('/crud-paket-koin/list-paket-koin')

    else:        
        formBuatPaket = BuatPaketKoin()

    return render(request, 'create_paket_koin.html', {'form' : BuatPaketKoin, "role" : role})

    

def updatePaketKoin(request, slug):
    if (request.session['role'] == ['admin']):
        role = "admin"
        form = UpdatePaketKoin(request.POST, request.FILES)
        cursor = connection.cursor()
        result = []

        cursor.execute("SELECT * FROM hiday.PAKET_KOIN WHERE jumlah_koin="+ str(slug)+ ";")
        result = cursor.fetchone()

        context = {
            'jumlah_koin' : result[0],
            'harga' : result[1]
        }

        if (form.is_valid and request.method == 'POST'):
            # jumlahkoin = form.data.get('JumlahKoin')
            harga = form.data.get('Harga')

            try:
                cursor.execute('UPDATE hiday.PAKET_KOIN SET harga='+ harga +'WHERE jumlah_koin ='+ "".join(slug)+';')
            
            except Exception as e:
                print(e)
                cursor.close()

            finally:
                cursor.close()
            return HttpResponseRedirect('/crud-paket-koin/list-paket-koin')

        return render(request, 'update_paket_koin.html', {'form' : UpdatePaketKoin, "role" : role, "result" : context})
    
    else:
        role = "pengguna"

    return render(request, 'update_paket_koin.html', {'form' : UpdatePaketKoin, "role" : role})

def deletePaketKoin(request, slug):
    if (request.session['role'] == ['admin']):
        role = "admin"
        form = DeletePaketKoin(request.POST, request.FILES)
        cursor = connection.cursor()
        
        result = []

        cursor.execute("SELECT * FROM hiday.PAKET_KOIN WHERE jumlah_koin="+ str(slug)+ ";")
        result = cursor.fetchone()

        context = {
            'jumlah_koin' : result[0],
            'harga' : result[1]
        }

       
        if (form.is_valid and request.method == 'POST'):
            try:
                cursor.execute("DELETE FROM hiday.PAKET_KOIN WHERE jumlah_koin ="+ "".join(slug)+";")
            
            except Exception as e:
                print(e)
                cursor.close()

            finally:
                cursor.close()
            return HttpResponseRedirect('/crud-paket-koin/list-paket-koin')

        return render(request, 'form_delete_paket_koin.html', {'form' : DeletePaketKoin, "role" : role, "result" : context})
    
    else:
        role = "pengguna"

    return render(request, 'form_delete_paket_koin.html', {'form' : DeletePaketKoin, "role" : role})

web-project/crud_paket_koin/templates/create_paket_koin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/list_paket_koin.css' %}">

  <title>TK3-F04</title>
</head>

<body>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}
    <h1>Form Paket Koin</h1>

    <form action="" method="post" onsubmit = "return validateForm()">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Buat">

    </form>
    
    {% endif %}


</body>

<script>
  function validateForm() {
    
    var y = document.forms["form"]['Harga'].value;
    var x = document.forms["form"]['Jumlah'].value;
    if (y == "") {
        alert("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu");
        return false;
    }
    if (x == "") {
        alert("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu");
        return false;
    }
  } 
</script>

</html>

web-project/crud_paket_koin/templates/form_delete_paket_koin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/list_paket_koin.css' %}">

  <title>TK3-F04</title>
</head>

<body>
    <h1>Delete Paket Koin</h1>
    {% if role == 'admin' %}
    {% include 'navbar.html' %}

    <h2>Anda Yakin Ingin Menghapus Paket Koin?</h2>
    

    <form action="" method="post" name="form">
        {% csrf_token %}
        <div class="container" align="center">
          <label for="id_JumlahKoin">Jumlah Koin</label>
          </br>
            <input type="number" class="form-control" name="JumlahKoin" value="{{ result.jumlah_koin }}" disabled>
            </br>
            <div align="center">
                <button type="submit">Delete</button>
                <a href="/crud-paket-koin/list-paket-koin">Cancel</a>
            </div>
        </div>
    </form>
          
    {% endif %}

</body>

</html>

web-project/crud_paket_koin/templates/list_paket_koin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/list_paket_koin.css' %}">

  <title>TK3-F04</title>
</head>

<body>
  
    <h1>List Paket Koin</h1>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}
    <table>
        <tr>
        <th>No</th>
        <th>Paket Koin</th>
        <th>Harga</th>
        <th>Action</th>
        </tr>

        {% for no, res in result %}
        <tr>
            <th>{{ no }}</th>
            <th>{{ res.jumlah_koin }}</th>
            <th>{{ res.harga }}</th>
            <th>
                <!-- <button class="button"> -->
                    <a href="update-paket-koin/{{ res.jumlah_koin }}">Update</a>
                <!-- </button> -->
                <!-- <button class="button"> -->
                    {% for cob in coba %}
                    {% if res.jumlah_koin == cob %}
                    <a href="delete-paket-koin/{{ res.jumlah_koin }}">Delete</a>

                    <!-- <form action="" method="post" name="form">
                        {% csrf_token %}
                        <div class="container" align="center">
                            </br>
                            <input type="number" class="form-control" name="JumlahKoin" value="{{ res.jumlah_koin }}" disabled>
                            </br>
                            <div align="center">
                            <button type="submit">Hapus</button>
                            </div>
                        </div>
                    </form> -->
                    {% endif %}
                    {% endfor %}
                <!-- </button> -->
            </th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if role == 'pengguna' %}
    {% include 'navbar.html' %}

    <table>
        <tr>
        <th>No</th>
        <th>Paket Koin</th>
        <th>Harga</th>
        <th>Action</th>
        </tr>

        {% for no, res in result %}
        <tr>
            <th>{{ no }}</th>
            <th>{{ res.jumlah_koin }}</th>
            <th>{{ res.harga }}</th>
            <th>
                <!-- <button class="button"> -->
                <a href="/cr-transaksi-pembelian-koin/form-transaksi-paket-koin/{{ res.jumlah_koin }}">Beli</a>
                <!-- </button> -->
            </th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>

</html>

web-project/crud_paket_koin/templates/update_paket_koin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/list_paket_koin.css' %}">

  <title>TK3-F04</title>
</head>

<body>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}
    <h1>Update Paket Koin</h1>

    <form action="" method="post" name="form" onsubmit = "return validateForm()">
        {% csrf_token %}
        <div class="container" align="center">
          <label for="id_JumlahKoin">Jumlah Koin</label>
          </br>
          <input type="number" class="form-control" name="JumlahKoin" value="{{ result.jumlah_koin }}" disabled>
          </br>
          <label for="id_Harga">Harga</label>
          </br>
          <input type="number" class="form-control" placeholder="Masukkan Harga" name="Harga">
          </br>
          <div align="center">
            <button type="submit">Simpan</button>
          </div>
        </div>
    </form>    
    {% endif %}

</body>

<script>
  function validateForm() {
      var y = document.forms["form"]['Harga'].value;
      if (y == "") {
          alert("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu");
          return false;
      }
  } 
</script>

</html>