web-project/BASDAT_TK3_F04/urls.py
from django.contrib import admin
from django.urls import include, path
from django import urls
from cr_histori_hewan.views import list_histori_hewan, produksi_hewan

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('crud-produk/', include('crud_produk.urls')),
    path('crud-paket-koin/', include('crud_paket_koin.urls')),
    path('cr-transaksi-pembelian-koin/', include('cr_transaksi_pembelian_koin.urls')),
    path('cr-transaksi-upgrade-lumbung/', include('cr_transaksi_update_lumbung.urls')),
    path('cr-histori-tanaman/', include('cr_histori_tanaman.urls')),
    path('crud-pesanan/', include('crud_pesanan.urls')),
    path('cr-histori-hewan/', include('cr_histori_hewan.urls')),
    path('cr-histori-penjualan/', include('cr_histori_penjualan.urls')),
    path('crud-produksi/', include('crud_produksi.urls')),
    path('cr-histori-pmakanan/', include('cr_histori_pmakanan.urls')),
    path('crud-aset/', include('crud_aset.urls')),
    path('r-koleksi-aset/', include('r_koleksi_aset.urls')),
    path('cr-transaksi-pembelian-aset/', include('cr_transaksi_pembelian_aset.urls')),
]

web-project/crud_produk/urls.py
from django.urls import path

from . import views

app_name = 'crud_produk'

urlpatterns = [
    path('list-produk', views.listProduk, name='list-produk'),
    path('buat-produk', views.buatProduk, name='buat-produk'),
    path('ubah-produk/<slug:slug>', views.ubahProduk, name='ubah-produk'),
    path('delete-produk/<slug:slug>', views.deleteProduk, name='delete-produk'),
    ]

web-project/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='landing'),
    path('registrasi', views.registrasi, name='registrasi'),
    path('registrasi-pengguna', views.registrasiPengguna, name='registrasi-pengguna'),
    path('registrasi-admin', views.registrasiAdmin, name='registrasi-admin'),
    path('login', views.login, name='login'),
    path('profile', views.loggedInView, name='view'),
    path('logout', views.logout, name='logout'),
    path('index', views.login, name='home'),
    path('isi-lumbung', views.isiLumbung, name='isi-lumbung'),
]

web-project/crud_produk/models.py
from django.db import models

# Create your models here.

web-project/crud_aset/forms.py
from django import forms

class BuatDekorasi(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    HargaJual = forms.IntegerField(label='HargaJual')

class BuatBibitTanaman(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    DurasiPanen = forms.TimeField(label='DurasiPanen')

class BuatKandang(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    KapasitasMaks = forms.IntegerField(label='KapasitasMaks')
    JenisHewan = forms.CharField(label='JenisHewan', max_length=50)

class BuatHewan(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    DurasiProduksi = forms.TimeField(label='DurasiProduksi')

class BuatAlatProduksi(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    KapasitasMaks = forms.IntegerField(label='KapasitasMaks')

class BuatPetakSawah(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')

class UbahDekorasi(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50, disabled=True, required=False)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    HargaJual = forms.IntegerField(label='HargaJual')

class UbahBibitTanaman(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50, disabled=True, required=False)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    DurasiPanen = forms.TimeField(label='DurasiPanen')

class UbahKandang(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50, disabled=True, required=False)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    KapasitasMaks = forms.IntegerField(label='KapasitasMaks')
    JenisHewan = forms.CharField(label='JenisHewan', max_length=50, disabled=True, required=False)

class UbahHewan(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50, disabled=True, required=False)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    DurasiProduksi = forms.TimeField(label='DurasiProduksi')
    IDKandang = forms.CharField(label='IDKandang', max_length=5, disabled=True, required=False)

class UbahAlatProduksi(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50, disabled=True, required=False)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')
    KapasitasMaks = forms.IntegerField(label='KapasitasMaks')

class UbahPetakSawah(forms.Form):
    ID = forms.CharField(label='ID', max_length=5, disabled=True, required=False)
    Nama = forms.CharField(label='Nama', max_length=50, disabled=True, required=False)
    MinimumLevel = forms.IntegerField(label='MinimumLevel')
    HargaBeli = forms.IntegerField(label='HargaBeli')

web-project/crud_produk/forms.py
from django import forms

class BuatProduk(forms.Form):
    IdProduk = forms.CharField(label='ID', max_length=5)
    Nama = forms.CharField(label='Nama', max_length=50)
    HargaJual = forms.IntegerField(label='Harga')
    SifatProduk = forms.CharField(label='Sifat', max_length=20)

class UbahProduk(forms.Form):
    HargaJual = forms.IntegerField(label='Harga')
    SifatProduk = forms.CharField(label='Sifat', max_length=20)

web-project/crud_produk/views.py
from traceback import print_tb
from django.shortcuts import render
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.db import connection
from collections import namedtuple
from .forms import *

def tupleFetch(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def listProduk(request):
   if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        resultt = []

        try:
            # cursor.execute("SET SEARCH_PATH TO HIDAY")
            if (request.session['role'] == ['admin']):
                role = "admin"

                cursor.execute("SELECT id_produk FROM hiday.DETAIL_PESANAN")
                resultt = tupleFetch(cursor)

                cursor.execute("SELECT id_produk FROM hiday.LUMBUNG_MEMILIKI_PRODUK")
                resultt.append(tupleFetch(cursor))

                cursor.execute("SELECT id_produk_hewan FROM hiday.HEWAN_MENGHASILKAN_PRODUK_HEWAN")
                resultt.append(tupleFetch(cursor))

                cursor.execute("SELECT id_hasil_panen FROM hiday.BIBIT_TANAMAN_MENGHASILKAN_HASIL_PANEN")
                resultt.append(tupleFetch(cursor))

                # print(resultt)
                # dataAdmin = namedtuple('ResultAdmin',result)

                idGabisaDelete = []
                for i in range(len(resultt)):
                    idGabisaDelete.append(resultt[i][0])

                # print(idGabisaDelete)

                cursor.execute("SELECT id, nama, harga_jual, sifat_produk, CASE WHEN id LIKE '%HP%' THEN 'Hasil Panen' WHEN id LIKE '%PH%' THEN 'Produk Hewan' WHEN id LIKE '%PM%' THEN 'Produk Makanan' END AS jenisproduk FROM hiday.PRODUK")
                desc = cursor.description
                nt_result = []
                for col in desc:
                    nt_result.append(col[0])
                # nt_result = namedtuple('Result', [col[0] for col in desc])
                nt_result.append("canDelete")

                resultAdmin = namedtuple('ResultAdmin',nt_result)

                result = []
                for row in cursor.fetchall():
                    if row[0] in idGabisaDelete:
                        result.append(resultAdmin(row[0],row[1],row[2],row[3],row[4],'False'))
                    else:
                        result.append(resultAdmin(row[0],row[1],row[2],row[3],row[4],'True'))

                print(result)

                temp = {}
                for i in range(len(result)):
                    temp[i+1] = result[i]
                    resultNum = list(temp.items())

                return render(request, 'list_produk.html', {"result" : resultNum, "role" : role})

            else:
                role = "pengguna"
                cursor.execute("SELECT id, nama, harga_jual, sifat_produk, CASE WHEN id LIKE '%HP%' THEN 'Hasil Panen' WHEN id LIKE '%PH%' THEN 'Produk Hewan' WHEN id LIKE '%PM%' THEN 'Produk Makanan' END AS jenisproduk FROM hiday.PRODUK")
                result = tupleFetch(cursor)
                temp = {}
                for i in range(len(result)):
                    temp[i+1] = result[i]
                    resultNum = list(temp.items())
                
                return render(request, 'list_produk.html', {"result" : resultNum, "role" : role})

        except Exception as e:
            print(e)
        
        finally:
            cursor.close()

   else:
        return HttpResponseRedirect('/login')

def buatProduk(request):
    if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        try:
            if (request.session['role'] == ['admin']):
                role = "admin"
                form = BuatProduk(request.POST, request.FILES)

                if (form.is_valid and request.method == 'POST'):
                    idproduk = form.data.get("IdProduk")
                    nama = form.data.get("Nama")
                    hargajual = form.data.get("HargaJual")
                    sifat = form.data.get("SifatProduk")
                    checker = idproduk

                    # print(idproduk)
                    # print(nama)
                    # print(hargajual)
                    # print(sifat)
                    
                    # cursor.execute("SET SEARCH_PATH TO HIDAY")
                    if (checker == "HP"):
                        cursor.execute("SELECT id FROM hiday.PRODUK WHERE id LIKE'HP%' ORDER BY id DESC LIMIT 1")
                    
                    elif (checker == "PH"):
                        cursor.execute("SELECT id FROM hiday.PRODUK WHERE id LIKE'PH%' ORDER BY id DESC LIMIT 1")

                    else:
                        cursor.execute("SELECT id FROM hiday.PRODUK WHERE id LIKE'PM%' ORDER BY id DESC LIMIT 1")
                    
                    result = cursor.fetchone()
                    # cursor.execute("SET SEARCH_PATH TO public")

                    # print(result)
                    resultt = result[0]
                    resultt = resultt[2:]
                    # print(resultt)
                    idAngka = int(resultt) + 1
                    idproduk = "%s%03d" % (idproduk, idAngka)

                    # cursor.execute("SET SEARCH_PATH TO HIDAY")
                    cursor.execute("INSERT INTO hiday.PRODUK VALUES ('" + idproduk + "', '" + nama + "', '" + hargajual + "', '" + sifat + "')")

                    if (checker == "HP"):
                        cursor.execute("INSERT INTO hiday.HASIL_PANEN VALUES ('" + idproduk + "')")

                    elif (checker == "PH"):
                        cursor.execute("INSERT INTO hiday.PRODUK_HEWAN VALUES ('" + idproduk + "')")

                    else:
                        cursor.execute("INSERT INTO hiday.PRODUK_MAKANAN VALUES ('" + idproduk + "')")

                    # cursor.execute("SET SEARCH_PATH TO public")
                    cursor.close()
                    return HttpResponseRedirect('/crud-produk/list-produk')
                
                return render(request, 'buat_produk.html', {"form" : BuatProduk, "role" : role})

            else:
                role = "pengguna"
                return render(request, 'buat_produk.html', {"form" : BuatProduk, "role" : role})
            
        except Exception as e:
            print(e)            
        
    else:
        return HttpResponseRedirect('/login')

def ubahProduk(request, slug):
    if (request.session['role'] == ['admin']):
        role = "admin"
        form = UbahProduk(request.POST, request.FILES)
        cursor = connection.cursor()
        result = []

        # cursor.execute("SET SEARCH_PATH TO HIDAY")
        cursor.execute("SELECT id, nama, harga_jual, sifat_produk, CASE WHEN id LIKE '%HP%' THEN 'Hasil Panen' WHEN id LIKE '%PH%' THEN 'Produk Hewan' WHEN id LIKE '%PM%' THEN 'Produk Makanan' END AS jenisproduk FROM hiday.PRODUK WHERE id = '" + ''.join(slug) + "'")
        result = cursor.fetchone()
        # cursor.execute("SET SEARCH_PATH TO public")
        # print(result)

        context = {
            'id' : result[0],
            'nama' : result[1],
            'hargajual' : result[2],
            'sifat' : result[3],
            'jenisproduk' : result[4]
        }

        if (form.is_valid and request.method == 'POST'):
            hargajual = form.data.get("HargaJual")
            sifat = form.data.get("SifatProduk")

            # cursor.execute("SET SEARCH_PATH TO HIDAY")
            cursor.execute("UPDATE hiday.PRODUK SET harga_jual = '" + hargajual + "', sifat_produk = '" + sifat + "' WHERE id = '" + ''.join(slug) + "'")
            # cursor.execute("SET SEARCH_PATH TO public")
            cursor.close()

            return HttpResponseRedirect('/crud-produk/list-produk')
        
        return render(request, 'ubah_produk.html', {"form" : UbahProduk, "role" : role, "result" : context})

    else:
        role = "pengguna"
    
    return render(request, 'ubah_produk.html', {"form" : UbahProduk, "role" : role})

def deleteProduk(request, slug):
    if (request.session['role'] == ['admin']):
        role = "admin"
        cursor = connection.cursor()
        # cursor.execute("SET SEARCH_PATH TO HIDAY")
        cursor.execute("DELETE FROM hiday.PRODUK WHERE id = '" + ''.join(slug) + "'")
        # cursor.execute("SET SEARCH_PATH TO public")
        cursor.close()
    else:
        role = "pengguna"
    
    return HttpResponseRedirect('/crud-produk/list-produk')

web-project/crud_produk/templates/buat_produk.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/buat_produk.css' %}">

  <title>TK3-F04</title>
</head>

<body>
    <h1>Form Buat Produk</h1>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}

    <form name="form" action = "" method = "POST" onsubmit = "return validateForm()">
        {% csrf_token %}
        <div class="container" align='center'>
            <label for="id_IdProduk">Jenis Produk</label>
            </br>
            <select id="id_ID" name="IdProduk">
                <option value="HP">Hasil Panen</option>
                <option value="PH">Produk Hewan</option>
                <option value="PM">Produk Makanan</option>
              </select>
            </br>
            <label for="id_Nama">Nama</label>
            </br>
            <input type="text" class="form-control" placeholder="Harap diisi" name="Nama" >
            </br>
            <label for="id_HargaJual">Harga Jual</label>
            </br>
            <input type="number" class="form-control" placeholder="Harap diisi" name="HargaJual">
            <p id="alert"></p>
            </br>
            <label for="id_SifatProduk">Sifat Produk</label>
            </br>
            <input type="text" class="form-control" placeholder="Harap diisi" name="SifatProduk" >
            </br>
            <div align='center'>
                <button type='submit'>Buat</button>      
            </div>
        </div> 
    </form>

    {% endif %}

    {% if role == 'pengguna' %}
    {% include 'navbar.html' %}

    <h1>Pengguna tidak dapat buat Produk</h1>
    {% endif %}

</body>

<script>
    function validateForm() {
        var x = document.forms["form"]['Nama'].value;
        var y = document.forms["form"]['HargaJual'].value;
        var z = document.forms["form"]['SifatProduk'].value;
        if (x == "" || y == "" || z == "") {
            alert("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu");
            return false;
        } 
    } 
</script>

</html>

web-project/crud_produk/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
    {% for res in result %}
        <p>Email: {{ res.email }}</p>
    {% endfor %}
{% endblock content %}

web-project/crud_produk/templates/list_produk.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/list_produk.css' %}">

  <title>TK3-F04</title>
</head>

<body>
  
    <h1>List Produk</h1>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}
    <table>
        <tr>
        <th>No</th>
        <th>Jenis</th>
        <th>Nama</th>
        <th>Harga Jual</th>
        <th>Sifat</th>
        <th>Action</th>
        </tr>

        {% for no, res in result %}
        <tr>
            <th>{{ no }}</th>
            <th>{{ res.jenisproduk }}</th>
            <th>{{ res.nama }}</th>
            <th>{{ res.harga_jual }}</th>
            <th>{{ res.sifat_produk }}</th>
            <th><a href="ubah-produk/{{ res.id }}">Update</a> <br>
            {% if res.canDelete == 'True' %}
                <a href="delete-produk/{{ res.id }}">Delete</a>
            {% endif %}
            </th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if role == 'pengguna' %}
    {% include 'navbar.html' %}

    <table>
        <tr>
        <th>No</th>
        <th>Jenis</th>
        <th>Nama</th>
        <th>Harga Jual</th>
        <th>Sifat</th>
        </tr>

        {% for no, res in result %}
        <tr>
            <th>{{ no }}</th>
            <th>{{ res.jenisproduk }}</th>
            <th>{{ res.nama }}</th>
            <th>{{ res.harga_jual }}</th>
            <th>{{ res.sifat_produk }}</th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>

</html>

web-project/crud_produk/templates/ubah_produk.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/buat_produk.css' %}">

  <title>TK3-F04</title>
</head>

<body>
    <h1>Form Ubah Produk</h1>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}

    <form action = "" method = "POST" name="form" onsubmit = "return validateForm()">
        {% csrf_token %}
        <div class="container" align='center'>
            <label for="id_ID">Jenis Produk</label>
            </br>
            <input type="text" class="form-control" placeholder="Jenis Produk yang Dipilih" name="JenisProduk" value="{{ result.jenisproduk }}"disabled>
            </br>
            <label for="id_Nama">Nama</label>
            </br>
            <input type="text" class="form-control" placeholder="Nama Produk yang Dipilih" name="Nama" value="{{ result.nama }}"disabled>
            </br>
            <label for="id_HargaJual">Harga Jual</label>
            </br>
            <input type="number" class="form-control" placeholder="Harap diisi" name="HargaJual">
            </br>
            <label for="id_SifatProduk">Sifat Produk</label>
            </br>
            <input type="text" class="form-control" placeholder="Harap diisi" name="SifatProduk">
            </br>
            <div align='center'>
                <button type='submit'>Simpan</button>      
            </div>
        </div>
    </form>

    {% endif %}

    {% if role == 'pengguna' %}
    {% include 'navbar.html' %}

    <h1>Pengguna tidak dapat mengubah Produk</h1>

    {% endif %}

</body>

<script>
    function validateForm() {
        var y = document.forms["form"]['HargaJual'].value;
        var z = document.forms["form"]['SifatProduk'].value;
        if (y == "" || z == "") {
            alert("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu");
            return false;
        }
    } 
</script>

</html>