web-project/BASDAT_TK3_F04/urls.py
from django.contrib import admin
from django.urls import include, path
from django import urls
from cr_histori_hewan.views import list_histori_hewan, produksi_hewan

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('crud-produk/', include('crud_produk.urls')),
    path('crud-paket-koin/', include('crud_paket_koin.urls')),
    path('cr-transaksi-pembelian-koin/', include('cr_transaksi_pembelian_koin.urls')),
    path('cr-transaksi-upgrade-lumbung/', include('cr_transaksi_update_lumbung.urls')),
    path('cr-histori-tanaman/', include('cr_histori_tanaman.urls')),
    path('crud-pesanan/', include('crud_pesanan.urls')),
    path('cr-histori-hewan/', include('cr_histori_hewan.urls')),
    path('cr-histori-penjualan/', include('cr_histori_penjualan.urls')),
    path('crud-produksi/', include('crud_produksi.urls')),
    path('cr-histori-pmakanan/', include('cr_histori_pmakanan.urls')),
    path('crud-aset/', include('crud_aset.urls')),
    path('r-koleksi-aset/', include('r_koleksi_aset.urls')),
    path('cr-transaksi-pembelian-aset/', include('cr_transaksi_pembelian_aset.urls')),
]

web-project/cr_histori_pmakanan/urls.py
from django.urls import path

from . import views

app_name = 'cr_histori_pmakanan'

urlpatterns = [
    path('list-histori-pmakanan', views.listHistori, name='list-produksi'),
    path('buat-histori-pmakanan', views.buatProduksi, name='buat-produksi'),
    ]

web-project/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='landing'),
    path('registrasi', views.registrasi, name='registrasi'),
    path('registrasi-pengguna', views.registrasiPengguna, name='registrasi-pengguna'),
    path('registrasi-admin', views.registrasiAdmin, name='registrasi-admin'),
    path('login', views.login, name='login'),
    path('profile', views.loggedInView, name='view'),
    path('logout', views.logout, name='logout'),
    path('index', views.login, name='home'),
    path('isi-lumbung', views.isiLumbung, name='isi-lumbung'),
]

web-project/cr_histori_pmakanan/models.py
from django.db import models

# Create your models here.

web-project/cr_histori_pmakanan/forms.py
from django import forms

class BuatProduksi(forms.Form):
    IdProduk = forms.CharField(label='IdProduk', max_length=5)
    Jumlah = forms.IntegerField(label='Jumlah')
    XP = forms.IntegerField(label='XP')

web-project/cr_histori_pmakanan/views.py
from time import time
from django.shortcuts import render
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.db import connection
from collections import namedtuple
from .forms import *
from datetime import datetime
from django.contrib import messages

def tupleFetch(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def listHistori(request):
   if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        role =''
        try:
            # cursor.execute("SET SEARCH_PATH TO HIDAY")
            if (request.session['role'] == ['admin']):    
                cursor.execute("SELECT HP.email, HP.waktu_awal, HP.waktu_selesai, HP.jumlah, HP.xp, P.nama as namaproduk, A.nama as asetalat from hiday.HISTORI_PRODUKSI HP JOIN hiday.HISTORI_PRODUKSI_MAKANAN HPM ON HP.email = HPM.email AND HP.waktu_awal = HPM.waktu_awal JOIN hiday.PRODUK P ON HPM.id_produk_makanan = P.id JOIN hiday.ASET A ON HPM.id_alat_produksi = A.id")
                result = tupleFetch(cursor)    
                role = "admin"

            else:
                email = str(request.session['email'][0])
                cursor.execute("SELECT HP.waktu_awal, HP.waktu_selesai, HP.jumlah, HP.xp, P.nama as namaproduk, A.nama as asetalat from hiday.HISTORI_PRODUKSI HP JOIN hiday.HISTORI_PRODUKSI_MAKANAN HPM ON HP.email = HPM.email AND HP.waktu_awal = HPM.waktu_awal JOIN hiday.PRODUK P ON HPM.id_produk_makanan = P.id JOIN hiday.ASET A ON HPM.id_alat_produksi = A.id AND HPM.email  = '" + ''.join(email) + "'")
                result = tupleFetch(cursor) 
                role = "pengguna"

        except Exception as e:
            print(e)
        
        finally:
            cursor.close()
            temp = {}
            for i in range(len(result)):
                temp[i+1] = result[i]
            resultNum = list(temp.items())

        return render(request, 'list_histori_pmakanan.html', {"result" : resultNum, "role" : role})

   else:
        return HttpResponseRedirect('/login')

def buatProduksi(request):
    if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        try:
            if (request.session['role'] == ['admin']):
                role = "admin"
                return render(request, 'buat_histori_pmakanan.html', {"form" : BuatProduksi, "role" : role})

            else:
                role = "pengguna"
                form = BuatProduksi(request.POST, request.FILES)
                cursor = connection.cursor()
                result = []

                # cursor.execute("SET SEARCH_PATH TO HIDAY")
                cursor.execute("SELECT id, nama FROM hiday.PRODUK WHERE id LIKE'PM%'")
                result = tupleFetch(cursor)
                # cursor.execute("SET SEARCH_PATH TO public")

                # print(result)

                if (form.is_valid and request.method == 'POST'):
                    idproduk = form.data.get("IdProduk")
                    jumlah = form.data.get("Jumlah")
                    xp = str(5 * int(jumlah))

                    # print(idproduk)
                    # print(jumlah)
                    # print(xp)

                    email = request.session['email'][0]

                    # cursor.execute("SET SEARCH_PATH TO HIDAY")

                    cursor.execute("SELECT jumlah, id_produk FROM hiday.PRODUK_DIBUTUHKAN_OLEH_PRODUK_MAKANAN WHERE id_produk_makanan = '" + idproduk + "'")
                    result = cursor.fetchone()

                    jumlahdibutuhkan = result[0]
                    produkdibutuhkan = result[1]
                    # print(jumlahdibutuhkan)
                    # print(produkdibutuhkan)

                    # cursor.execute("SELECT jumlah FROM LUMBUNG_MEMILIKI_PRODUK WHERE id_lumbung = '" + email + "' AND id_produk = '" + produkdibutuhkan + "'")
                    cursor.execute("SELECT id_produk, jumlah FROM hiday.LUMBUNG_MEMILIKI_PRODUK WHERE id_lumbung = '" + email + "'")
                    result = tupleFetch(cursor)

                    checkerSatu = False #ngecek usernya punya produk buat produksi atauga
                    jumlahdipengguna = 0
                    for i in range(len(result)):
                        # print(result[i][0])
                        if (produkdibutuhkan == result[i][0]):
                            jumlahdipengguna = result[i][1]
                            checkerSatu = True

                    # jumlahdipengguna = result[0]
                    # print(jumlahdipengguna)

                    cursor.execute("SELECT id_alat_produksi FROM hiday.PRODUKSI WHERE id_produk_makanan = '" + idproduk + "'")
                    result = cursor.fetchone()

                    alatproduksi = result[0]
                    # print(alatproduksi)

                    cursor.execute("SELECT id_koleksi_aset FROM hiday.KOLEKSI_ASET_MEMILIKI_ASET WHERE id_aset = '" + alatproduksi + "'")
                    result = tupleFetch(cursor)
                    # print(result)

                    checkerDua = False #ngecek usernya punya alat(aset) buat produksi atauga
                    for i in range(len(result)):
                        # print(result[i][0])
                        if (email == result[i][0]):
                            checkerDua = True

                    waktuAwal = str(datetime.now())
                    waktuSelesai = str(datetime.now())

                    print(checkerSatu)
                    print(checkerDua)

                    if (int(jumlahdipengguna) < int(jumlahdibutuhkan) * int(jumlah)):
                        cursor.execute("SELECT id, nama FROM hiday.PRODUK WHERE id LIKE'PM%'")
                        result = tupleFetch(cursor)
                        # cursor.execute("SET SEARCH_PATH TO public")
                        cursor.close()
                        # print("GAGALLL")
                        return render(request, 'buat_histori_pmakanan.html', {"form" : BuatProduksi, "role" : role, "result" : result, "gagal" : "gapunyabahan"})

                    if ((int(jumlahdipengguna) >= int(jumlahdibutuhkan) * int(jumlah)) and (checkerSatu) and (checkerDua)):
                        # print('Masuk')
                        cursor.execute("SET SEARCH_PATH TO HIDAY")
                        cursor.execute("INSERT INTO hiday.HISTORI_PRODUKSI VALUES ('" + email + "', '" + waktuAwal + "', '" + waktuSelesai + "', '" + jumlah + "' , '" + xp + "')")
                        cursor.execute("INSERT INTO hiday.HISTORI_PRODUKSI_MAKANAN VALUES ('" + email + "', '" + waktuAwal + "', '" + alatproduksi + "', '" + idproduk + "')")
                        cursor.execute("SET SEARCH_PATH TO public")
                        cursor.close()
                        return HttpResponseRedirect('/cr-histori-pmakanan/list-histori-pmakanan')
                    
                    cursor.execute("SELECT id, nama FROM hiday.PRODUK WHERE id LIKE'PM%'")
                    result = tupleFetch(cursor)
                    # cursor.execute("SET SEARCH_PATH TO public")
                    cursor.close()
                    return render(request, 'buat_histori_pmakanan.html', {"form" : BuatProduksi, "role" : role, "result" : result, "gagal" : "gapunyaaset"})

                    # return render(request, 'buat_histori_pmakanan.html', {"form" : BuatProduksi, "role" : role, "result" : result, "gagal" : "gagaga"})
                    # return HttpResponseRedirect('/crud-produk/list-produk')
                
                return render(request, 'buat_histori_pmakanan.html', {"form" : BuatProduksi, "role" : role, "result" : result, "gagal" : "tidak"})
            
        except Exception as e:
            print(e)            
        
    else:
        return HttpResponseRedirect('/login')

web-project/cr_histori_pmakanan/templates/buat_histori_pmakanan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/buat_histori_makanan.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

  <title>TK3-F04</title>
</head>

<body>
    <h1>Form Produksi Produk Makanan</h1>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}

    <h1>Admin tidak dapat Produksi Produk Makanan</h1>

    {% endif %}

    {% if role == 'pengguna' %}
    {% include 'navbar.html' %}

    {% if gagal == 'gapunyabahan' %}
        <body onload = "return alertt()">
    {% endif %}

    {% if gagal == 'gapunyaaset' %}
        <body onload = "return alerttdua()">
    {% endif %}

    <form action = "" method = "POST" name="form" onsubmit = "return validateForm()">
        {% csrf_token %}
        <div class="container" align='center'>
            <label for="id_IdProduk">ID Produk Makanan</label>
            <br>
            <select id="id_IdProduk" name="IdProduk">
                {% for res in result %}
                    <option value="{{ res.id }}">{{ res.nama }}</option>
                {% endfor %}
            </select>
            </br>

            <label for="id_Jumlah">Jumlah</label>
            </br>
            <input type="number" class="form-control" placeholder="Harap diisi" name="Jumlah" id="jmlh" onchange="countXP()">
            </br>
            
            <label for="id_XP">XP</label>
            </br>
            <input type="number" class="form-control" placeholder="" name="XP" id="xpp" disabled>
            </br>

            <div align='center'>
                <button type='submit'>Buat</button>      
            </div>
        </div>
    </form>

    {% endif %}

</body>

<script>
    function countXP() {
        document.getElementById("xpp").value = 5 * document.getElementById("jmlh").value;
    }

    function validateForm() {
        var y = document.forms["form"]['Jumlah'].value;
        if (y == "") {
            alert("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu");
            return false;
        }
    } 

    function alertt() {
        alert('Anda tidak memiliki bahan yang cukup, silahkan menambahkan produk yang akan digunakan sebagai bahan terlebih dahulu');
    }

    function alerttdua() {
        alert('Anda tidak memiliki aset (alat) yang dibutuhkan');
    }
</script>

</html>

web-project/cr_histori_pmakanan/templates/list_histori_pmakanan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/list_histori_makanan.css' %}">

  <title>TK3-F04</title>
</head>

<body>
  
    <h1>List Produk</h1>

    {% if role == 'admin' %}
    {% include 'navbar.html' %}
    <table>
        <tr>
        <th>No</th>
        <th>Email Pengguna</th>
        <th>Waktu Awal</th>
        <th>Waktu Selesai</th>
        <th>Jumlah</th>
        <th>XP</th>
        <th>Produk Makanan</th>
        <th>Alat Produksi</th>
        </tr>

        {% for no, res in result %}
        <tr>
            <th>{{ no }}</th>
            <th>{{ res.email }}</th>
            <th>{{ res.waktu_awal }}</th>
            <th>{{ res.waktu_selesai }}</th>
            <th>{{ res.jumlah }}</th>
            <th>{{ res.xp }}</th>
            <th>{{ res.namaproduk }}</th>
            <th>{{ res.asetalat }}</th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if role == 'pengguna' %}
    {% include 'navbar.html' %}

    <table>
        <tr>
            <th>No</th>
            <th>Waktu Awal</th>
            <th>Waktu Selesai</th>
            <th>Jumlah</th>
            <th>XP</th>
            <th>Produk Makanan</th>
            <th>Alat Produksi</th>
        </tr>

        {% for no, res in result %}
        <tr>
            <th>{{ no }}</th>
            <th>{{ res.waktu_awal }}</th>
            <th>{{ res.waktu_selesai }}</th>
            <th>{{ res.jumlah }}</th>
            <th>{{ res.xp }}</th>
            <th>{{ res.namaproduk }}</th>
            <th>{{ res.asetalat }}</th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>

</html>